version: '2'
services:
  admin-mysql:
    image: mysql:5.6
#    restart: always
    volumes:
      - ~/docker/admin/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1371271347
      - MYSQL_DATABASE=admin
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=32505856
